export interface ScenarioPreset {
  id: string;
  label: string;
  description: string;
  params: Record<string, unknown>;
}

export const scenarioPresets: ScenarioPreset[] = [
  {
    id: '2020-electorate',
    label: '2020 Electorate',
    description: 'Baseline 2020 presidential election, no adjustments',
    params: {
      baseElectionYear: '2020',
      baseRaceType: 'president',
      swingPoints: 0,
      turnoutChange: 0,
      swing_milwaukee_metro: 0,
      swing_madison_metro: 0,
      swing_fox_valley: 0,
      swing_rural: 0,
    },
  },
  {
    id: '2016-electorate',
    label: '2016 Electorate',
    description: 'Baseline 2016 presidential election, no adjustments',
    params: {
      baseElectionYear: '2016',
      baseRaceType: 'president',
      swingPoints: 0,
      turnoutChange: 0,
      swing_milwaukee_metro: 0,
      swing_madison_metro: 0,
      swing_fox_valley: 0,
      swing_rural: 0,
    },
  },
  {
    id: 'high-turnout',
    label: 'High Turnout',
    description: 'Differential high turnout: +20% Milwaukee, +15% Madison, +10% Fox Valley, +5% rural',
    params: {
      baseElectionYear: '2024',
      baseRaceType: 'president',
      swingPoints: 0,
      turnoutChange: 5,
      swing_milwaukee_metro: 0,
      swing_madison_metro: 0,
      swing_fox_valley: 0,
      swing_rural: 0,
      turnout_milwaukee_metro: 15,
      turnout_madison_metro: 10,
      turnout_fox_valley: 5,
      turnout_rural: 0,
    },
  },
  {
    id: 'low-turnout',
    label: 'Low Turnout',
    description: 'Differential low turnout: -20% Milwaukee, -15% Madison, -10% Fox Valley, -5% rural',
    params: {
      baseElectionYear: '2024',
      baseRaceType: 'president',
      swingPoints: 0,
      turnoutChange: -5,
      swing_milwaukee_metro: 0,
      swing_madison_metro: 0,
      swing_fox_valley: 0,
      swing_rural: 0,
      turnout_milwaukee_metro: -15,
      turnout_madison_metro: -10,
      turnout_fox_valley: -5,
      turnout_rural: 0,
    },
  },
  {
    id: 'd-wave-5',
    label: 'D Wave +5',
    description: '2024 baseline with D+5 statewide swing',
    params: {
      baseElectionYear: '2024',
      baseRaceType: 'president',
      swingPoints: 5,
      turnoutChange: 0,
      swing_milwaukee_metro: 0,
      swing_madison_metro: 0,
      swing_fox_valley: 0,
      swing_rural: 0,
    },
  },
  {
    id: 'r-wave-5',
    label: 'R Wave +5',
    description: '2024 baseline with R+5 statewide swing',
    params: {
      baseElectionYear: '2024',
      baseRaceType: 'president',
      swingPoints: -5,
      turnoutChange: 0,
      swing_milwaukee_metro: 0,
      swing_madison_metro: 0,
      swing_fox_valley: 0,
      swing_rural: 0,
    },
  },
  {
    id: 'milwaukee-surge',
    label: 'MKE Surge',
    description: 'High Milwaukee metro turnout (+20%), moderate Madison (+10%), baseline elsewhere',
    params: {
      baseElectionYear: '2024',
      baseRaceType: 'president',
      swingPoints: 0,
      turnoutChange: 0,
      swing_milwaukee_metro: 0,
      swing_madison_metro: 0,
      swing_fox_valley: 0,
      swing_rural: 0,
      turnout_milwaukee_metro: 20,
      turnout_madison_metro: 10,
      turnout_fox_valley: 0,
      turnout_rural: 0,
    },
  },
  {
    id: 'rural-mobilization',
    label: 'Rural Mobilize',
    description: 'High rural turnout (+15%), moderate Fox Valley (+10%), flat metro',
    params: {
      baseElectionYear: '2024',
      baseRaceType: 'president',
      swingPoints: 0,
      turnoutChange: 0,
      swing_milwaukee_metro: 0,
      swing_madison_metro: 0,
      swing_fox_valley: 0,
      swing_rural: 0,
      turnout_milwaukee_metro: 0,
      turnout_madison_metro: 0,
      turnout_fox_valley: 10,
      turnout_rural: 15,
    },
  },
];
