"""initial schema

Revision ID: 5f6667e84e0c
Revises: 
Create Date: 2026-02-26 23:10:13.755007

"""
from typing import Sequence, Union

from alembic import op
import geoalchemy2
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f6667e84e0c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ward_demographics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ward_id', sa.String(length=50), nullable=False),
    sa.Column('census_year', sa.Integer(), nullable=True),
    sa.Column('total_population', sa.Integer(), nullable=True),
    sa.Column('voting_age_population', sa.Integer(), nullable=True),
    sa.Column('white_pct', sa.Float(), nullable=True),
    sa.Column('black_pct', sa.Float(), nullable=True),
    sa.Column('hispanic_pct', sa.Float(), nullable=True),
    sa.Column('asian_pct', sa.Float(), nullable=True),
    sa.Column('college_degree_pct', sa.Float(), nullable=True),
    sa.Column('median_household_income', sa.Integer(), nullable=True),
    sa.Column('urban_rural_class', sa.String(length=20), nullable=True),
    sa.Column('population_density', sa.Float(), nullable=True),
    sa.Column('ward_vintage', sa.Integer(), nullable=False),
    sa.Column('data_source', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ward_demographics_ward_id'), 'ward_demographics', ['ward_id'], unique=False)
    op.create_table('ward_trends',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ward_id', sa.String(length=50), nullable=False),
    sa.Column('race_type', sa.String(length=50), nullable=False),
    sa.Column('trend_direction', sa.String(length=20), nullable=True),
    sa.Column('trend_slope', sa.Float(), nullable=True),
    sa.Column('trend_r_squared', sa.Float(), nullable=True),
    sa.Column('trend_p_value', sa.Float(), nullable=True),
    sa.Column('elections_analyzed', sa.Integer(), nullable=True),
    sa.Column('start_year', sa.Integer(), nullable=True),
    sa.Column('end_year', sa.Integer(), nullable=True),
    sa.Column('ward_vintage', sa.Integer(), nullable=False),
    sa.Column('computed_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ward_trends_ward_id'), 'ward_trends', ['ward_id'], unique=False)
    op.create_table('wards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ward_id', sa.String(length=50), nullable=False),
    sa.Column('ward_name', sa.String(length=255), nullable=False),
    sa.Column('municipality', sa.String(length=255), nullable=False),
    sa.Column('municipality_type', sa.String(length=20), nullable=True),
    sa.Column('county', sa.String(length=100), nullable=False),
    sa.Column('congressional_district', sa.String(length=10), nullable=True),
    sa.Column('state_senate_district', sa.String(length=10), nullable=True),
    sa.Column('assembly_district', sa.String(length=10), nullable=True),
    sa.Column('county_supervisory_district', sa.String(length=10), nullable=True),
    sa.Column('ward_vintage', sa.Integer(), nullable=False),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('area_sq_miles', sa.Float(), nullable=True),
    sa.Column('is_estimated', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ward_id')
    )
    op.create_index('idx_wards_county', 'wards', ['county'], unique=False)
    # idx_wards_geom is auto-created by GeoAlchemy2 when the geometry column is added
    op.create_index('idx_wards_municipality', 'wards', ['municipality'], unique=False)
    op.create_index('idx_wards_vintage', 'wards', ['ward_vintage'], unique=False)
    op.create_table('election_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ward_id', sa.String(length=50), nullable=False),
    sa.Column('election_year', sa.Integer(), nullable=False),
    sa.Column('election_date', sa.Date(), nullable=True),
    sa.Column('race_type', sa.String(length=50), nullable=False),
    sa.Column('race_name', sa.String(length=255), nullable=True),
    sa.Column('dem_candidate', sa.String(length=255), nullable=True),
    sa.Column('rep_candidate', sa.String(length=255), nullable=True),
    sa.Column('dem_votes', sa.Integer(), nullable=False),
    sa.Column('rep_votes', sa.Integer(), nullable=False),
    sa.Column('other_votes', sa.Integer(), nullable=False),
    sa.Column('total_votes', sa.Integer(), nullable=False),
    sa.Column('is_estimate', sa.Boolean(), nullable=False),
    sa.Column('reporting_unit_name', sa.String(length=500), nullable=True),
    sa.Column('data_source', sa.String(length=100), nullable=True),
    sa.Column('ward_vintage', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ward_id'], ['wards.ward_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ward_id', 'election_year', 'race_type', 'ward_vintage', name='idx_results_unique')
    )
    op.create_index('idx_results_vintage', 'election_results', ['ward_vintage'], unique=False)
    op.create_index('idx_results_year_race', 'election_results', ['election_year', 'race_type'], unique=False)
    op.create_index(op.f('ix_election_results_ward_id'), 'election_results', ['ward_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_election_results_ward_id'), table_name='election_results')
    op.drop_index('idx_results_year_race', table_name='election_results')
    op.drop_index('idx_results_vintage', table_name='election_results')
    op.drop_table('election_results')
    op.drop_index('idx_wards_vintage', table_name='wards')
    op.drop_index('idx_wards_municipality', table_name='wards')
    op.drop_index('idx_wards_county', table_name='wards')
    op.drop_table('wards')
    op.drop_index(op.f('ix_ward_trends_ward_id'), table_name='ward_trends')
    op.drop_table('ward_trends')
    op.drop_index(op.f('ix_ward_demographics_ward_id'), table_name='ward_demographics')
    op.drop_table('ward_demographics')
    # ### end Alembic commands ###
